BEGIN;

CREATE TABLE IF NOT EXISTS attendees (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    "emailAddress" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL UNIQUE,
    "githubUsername" VARCHAR(255) NOT NULL UNIQUE,
    avatar VARCHAR(500) NOT NULL
);

END;